sudo: required
services:
  - docker

before_install:
  - docker build -t andinianst93/complex-frontend -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true andinianst93/complex-frontend npm run test

after_success:
  - docker build -t andinianst93/multi-client ./client
  - docker build -t andinianst93/multi-nginx ./nginx
  - docker build -t andinianst93/multi-server ./server
  - docker build -t andinianst93/multi-worker ./worker
